### ISSUE TITLE
Error : Kibana did not load properly. Check the server output for more information.

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [dlumbrer/kbn_searchtables#9]
ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 5:0-87

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 7:0-86

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-dropdown-multiselect/dist/angularjs-dropdown-multiselect.min in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 9:0-123

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 3:13-84

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 9:12-82

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 22:4-110

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 23:4-106

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 24:4-96

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer.WMS in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 25:4-100

Unhandled rejection Error: Optimizations failure.

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 5:0-87

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 7:0-86

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-dropdown-multiselect/dist/angularjs-dropdown-multiselect.min in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 9:0-123

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 3:13-84

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 9:12-82

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 22:4-110

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 23:4-106

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 24:4-96

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer.WMS in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 25:4-100

    at LazyOptimizer.failedStatsToError (/Users/josephvedadi/Tools/kibana/src/optimize/base_optimizer.js:224:17)
    at Compiler.compiler.plugin.stats (/Users/josephvedadi/Tools/kibana/src/optimize/lazy/lazy_optimizer.js:42:24)
    at Compiler.applyPlugins (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:51:17)
    at /Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:279:5)
    at /Users/josephvedadi/Tools/kibana/node_modules/async/lib/async.js:52:16
Error: Optimizations failure.

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 5:0-87

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 7:0-86

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-dropdown-multiselect/dist/angularjs-dropdown-multiselect.min in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 9:0-123

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 3:13-84

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 9:12-82

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 22:4-110

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 23:4-106

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 24:4-96

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer.WMS in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 25:4-100

    at LazyOptimizer.failedStatsToError (/Users/josephvedadi/Tools/kibana/src/optimize/base_optimizer.js:224:17)
    at Compiler.compiler.plugin.stats (/Users/josephvedadi/Tools/kibana/src/optimize/lazy/lazy_optimizer.js:42:24)
    at Compiler.applyPlugins (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:51:17)
    at /Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:279:5)
    at /Users/josephvedadi/Tools/kibana/node_modules/async/lib/async.js:52:16
Error: Optimizations failure.

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 5:0-87

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 7:0-86

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-dropdown-multiselect/dist/angularjs-dropdown-multiselect.min in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 9:0-123

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 3:13-84

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 9:12-82

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 22:4-110

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 23:4-106

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 24:4-96

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer.WMS in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 25:4-100

    at LazyOptimizer.failedStatsToError (/Users/josephvedadi/Tools/kibana/src/optimize/base_optimizer.js:224:17)
    at Compiler.compiler.plugin.stats (/Users/josephvedadi/Tools/kibana/src/optimize/lazy/lazy_optimizer.js:42:24)
    at Compiler.applyPlugins (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:51:17)
    at /Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:279:5)
    at /Users/josephvedadi/Tools/kibana/node_modules/async/lib/async.js:52:16
Error: Optimizations failure.

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 5:0-87

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-slider/dist/rzslider.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 7:0-86

    ERROR in ./plugins/enhanced_tilemap/public/vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/angularjs-dropdown-multiselect/dist/angularjs-dropdown-multiselect.min in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public
     @ ./plugins/enhanced_tilemap/public/vis.js 9:0-123

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/formatcoords/index in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 3:13-84

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/mgrs/dist/mgrs.js in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 9:12-82

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition.css in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 22:4-110

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.MousePosition/src/L.Control.MousePosition in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 23:4-106

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 24:4-96

    ERROR in ./plugins/enhanced_tilemap/public/vislib/_map.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/bower_components/Leaflet.NonTiledLayer/src/NonTiledLayer.WMS in /Users/josephvedadi/Tools/kibana/plugins/enhanced_tilemap/public/vislib
     @ ./plugins/enhanced_tilemap/public/vislib/_map.js 25:4-100

    at LazyOptimizer.failedStatsToError (/Users/josephvedadi/Tools/kibana/src/optimize/base_optimizer.js:224:17)
    at Compiler.compiler.plugin.stats (/Users/josephvedadi/Tools/kibana/src/optimize/lazy/lazy_optimizer.js:42:24)
    at Compiler.applyPlugins (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:51:17)
    at /Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/josephvedadi/Tools/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/josephvedadi/Tools/kibana/node_modules/extract-text-webpack-plugin/index.js:279:5)
    at /Users/josephvedadi/Tools/kibana/node_modules/async/lib/async.js:52:16

**Comment by dlumbrer** [comment]
What version of kibana are you using?

Did you change the tag "version" of package.json?

Thx
